# BRENDA — source-context and interpretation audit

This supplementary analysis reviews the raw fields behind the common contract.
It does not modify normalized data, identify cleavage positions or look up
substrates in MEROPS. The adapter's concrete decisions are recorded by JSON
locator in `normalized/remarks_brenda.md`.

In [1]:
from pathlib import Path
import sys, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, HTML

here = Path.cwd().resolve()
ROOT = next(p for p in [here, *here.parents] if (p / "assets/tools/proteolysis_data_manager").is_dir())
sys.path.insert(0, str(ROOT / "assets/tools/proteolysis_data_manager/src"))
from proteolysis_data_manager.integration.kinetics.reader import load_kinetics_data
from proteolysis_data_manager.analysis.kinetics.overview import (
    table_inventory, missingness, species_coverage, parameter_summary,
    formatted_table, plot_parameters, plot_conditions,
)
DATA_ROOT = ROOT / "data/kinetics_datasets"
SERIES = ROOT / "assets/experiments/analysis/09_26/20_serum_proteolysis_calibration_max/notebooks/0_data_analysis_kinetics"
plt.rcParams.update({"figure.dpi": 110, "axes.spines.top": False,
                     "axes.spines.right": False, "axes.grid": True, "grid.alpha": .12})
def table(frame, limit=30):
    if len(frame) > limit:
        print(f"Preview: {limit} of {len(frame)} rows")
    display(HTML(formatted_table(frame, limit)))
def figure(fig):
    plt.show()
    plt.close(fig)

In [2]:
dataset = load_kinetics_data(DATA_ROOT)
view = dataset.measurements_view()
table(view.loc[view.value_relation.ne("eq"), ["measurement_id", "parameter_type", "value_relation", "value_numeric", "source_record_id"]], 25)
table(pd.DataFrame([{"scope": "All parameter families", "non_point_or_unresolved": int(view.value_numeric.isna().sum()),
    "reported_CI": int(view.ci_lower.notna().sum()), "reported_SD": int(view.sd.notna().sum())}]))

Preview: 25 of 792 rows

## Read source entries without cross-record pairing

Each locator identifies the source entry, not an independent experiment. The
same protein and PMID can describe several mutants, substrates, pH values or
temperatures. Protein-group associations and optimum fields must not silently
populate a specific assay. The rows below preserve the original value/comment. Unusual temperatures such
as the source entry reporting 378°C are retained for review, not corrected.

In [3]:
from proteolysis_data_manager.acquisition.kinetics.brenda import verify_snapshot
from proteolysis_data_manager.integration.kinetics.adapters.brenda import iter_records, PARAMETERS
receipt = verify_snapshot(DATA_ROOT)
raw_rows = []
for ec, record in iter_records(DATA_ROOT / receipt["raw_path"]):
    if not ec.startswith("3.4."):
        continue
    for family in PARAMETERS:
        for index, entry in enumerate(record.get(family) or []):
            raw_rows.append({"source_locator": f"data/{ec}/{family}/{index}", "family": family,
                "value_raw": str(entry.get("value") or ""), "comment_raw": str(entry.get("comment") or ""),
                "protein_links": len(set(map(str, entry.get("proteins") or []))),
                "reference_links": len(set(map(str, entry.get("references") or [])))})
raw = pd.DataFrame(raw_rows)
assert len(raw) == len(view)
table(raw.loc[raw.protein_links.ne(1)], 15)
table(raw.loc[raw.value_raw.str.contains(r"^-|[<>±]|\d\s*[-–]\s*\d", regex=True)], 15)

Preview: 15 of 199 rows

Preview: 15 of 1032 rows

## Reported mentions are not automatically resolved annotations

These lexical counts are inspection aids, not extracted cleavage sites or
assay classifications. In particular, a comment containing “cleavage” does not
establish a position or link a global kinetic parameter to that position.

In [4]:
patterns = {"cleavage_or_hydrolysis_mention": r"cleav|scissile|hydrolys",
    "serum_or_plasma_mention": r"serum|plasma", "buffer_mention": r"buffer",
    "variant_mention": r"mutant|wild.type|recombinant|variant",
    "optimum_or_storage_mention": r"optim|stability|storage|stored"}
table(pd.DataFrame([{"description": name, "source_entries": int(raw.comment_raw.str.contains(pattern, case=False, regex=True).sum())}
                    for name, pattern in patterns.items()]))
site_mentions = raw.loc[raw.comment_raw.str.contains(patterns["cleavage_or_hydrolysis_mention"], case=False, regex=True)]
table(site_mentions, 20)
table(raw.loc[raw.comment_raw.str.contains(patterns["serum_or_plasma_mention"], case=False, regex=True)], 20)

Preview: 20 of 521 rows

Preview: 20 of 104 rows

## Unit and condition rules

`Km`: mM → M (×0.001). `kcat`: s⁻¹. `kcat/Km`: inverse mM/time →
M⁻¹s⁻¹ (×1000). These are family defaults, not ratios computed from unrelated
rows. BRENDA has an inconsistent `mM/s` heading on its field-definition page;
the [search form](https://www.brenda-enzymes.org/search_result.php?a=305) specifies
inverse concentration/time. The manifest records the exact conversion rule.

Only a single unambiguous pH/°C scalar in the entry comment is read. Ranges,
conflicting mentions and optimum/storage/stability context remain null. General
enzyme optima and source tissue are not assay metadata.

**TODO:** review assay-method, matrix/mode, concentration and reported uncertainty
entry by entry where the source supplies evidence. This is curation, not imputation.
Do not introduce fragment searches or cross-family chemistry enrichment.

In [5]:
table(pd.DataFrame(dataset.metadata["unit_policy"].items(), columns=["source_field", "conversion"]))
table(view.loc[view.ph.notna() | view.temperature_c.notna(), ["parameter_type", "ph", "temperature_c", "conditions_raw", "source_record_id"]], 20)
table(view.loc[view.conditions_raw.fillna("").str.contains(r"optim|stability|storage|stored", case=False, regex=True),
               ["ph", "temperature_c", "conditions_raw", "source_record_id"]], 15)

Preview: 20 of 17374 rows